greeting:
  message: Hello Yaml
'%dev':
  quarkus:
    log:
      console:
        json: false
'%staging':
  quarkus:
    http:
      port: 8181
    log:
      level: INFO
      file:
        enabled : true
        handler:
          gelf:
            enabled: false
            host: localhost
            port: 12201